let playwright;try{playwright=require('playwright');}catch{playwright=require((process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES||'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules')+'/playwright');}const {chromium}=playwright;
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../dist');const types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.jpg':'image/jpeg'};
const server=http.createServer((req,res)=>{const file=path.join(root,req.url==='/'?'index.html':req.url.split('?')[0]);if(!file.startsWith(root)){res.writeHead(403);return res.end();}fs.readFile(file,(err,data)=>{res.writeHead(err?404:200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(err?'missing':data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||(fs.existsSync('/tmp/replicant-chromium/chromium')?'/tmp/replicant-chromium/chromium':chromium.executablePath()),headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text());});let passed=0;const pass=s=>{passed++;console.log('PASS',s);};try{
 await page.goto(`http://127.0.0.1:${port}`);await page.waitForFunction(()=>!document.getElementById('start').disabled,{},{timeout:30000});assert.equal(await page.locator('#boot').isVisible(),true);assert.equal(await page.locator('#hud').isVisible(),false);assert.equal(await page.locator('#boot').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(0, 0, 0)');await page.screenshot({path:'/tmp/replicant-start.png'});pass('black name entry screen loads local 3D assets');
 await page.locator('#name').fill('Chris');await page.locator('#start').click();await page.waitForFunction(()=>window.__game?.paused);assert.equal(await page.locator('#pause').isVisible(),true);assert.equal(await page.locator('#hud').isVisible(),true);assert.equal(await page.locator('#pilot').textContent(),'Chris');assert.equal(await page.locator('.controls>div').count(),16);pass('Start shows controls, Earth scene, name and health HUD');
 await page.locator('#resume').click();await page.waitForFunction(()=>!window.__game.paused);await page.waitForFunction(()=>window.__render.renderer.info.render.calls>0);const capture=await page.evaluate(()=>({lock:document.pointerLockElement?.id,earth:window.__render.planetMeshes.get(0).visible,meshes:window.__render.planetMeshes.size,draws:window.__render.renderer.info.render.calls}));assert.equal(capture.earth,true);assert.equal(capture.meshes,3000);assert.ok(capture.draws>5);pass('WebGL renders third-person space scene and 3,000 planet catalog');await page.screenshot({path:'/tmp/replicant-flight.png'});
 await page.waitForFunction(()=>window.__render.planetMeshes.get(1).visible&&window.__render.planetMeshes.get(2).visible);await page.evaluate(()=>{window.__game.targetPlanet=2999;});await page.waitForFunction(()=>window.__render.planetMeshes.get(2999).visible);await page.evaluate(()=>{window.__game.targetPlanet=1;});pass('distant nearby worlds and selected destination render beyond the old visibility cutoff');
 const pos=await page.evaluate(()=>[...window.__game.leader.pos]);await page.keyboard.down('w');await page.keyboard.down('d');await page.keyboard.down('Space');await page.waitForFunction(p=>{const a=window.__game.leader.pos;return a[0]>p[0]+10&&a[1]>p[1]+10&&a[2]<p[2]-10},pos);await page.keyboard.up('w');await page.keyboard.up('d');await page.keyboard.up('Space');pass('actual simultaneous W+D+Space input moves ship on three axes');
 await page.keyboard.press('Escape');await page.waitForFunction(()=>window.__game.paused);const frozen=await page.evaluate(()=>({pos:[...window.__game.leader.pos],time:window.__game.time}));await page.waitForTimeout(400);assert.deepEqual(await page.evaluate(()=>({pos:[...window.__game.leader.pos],time:window.__game.time})),frozen);assert.equal(await page.locator('#pause').isVisible(),true);pass('Escape pauses simulation and reveals control overlay');
 await page.locator('#resume').click();await page.waitForFunction(()=>!window.__game.paused);await page.keyboard.down('c');await page.waitForFunction(()=>window.__game.ships.length===2,{},{timeout:15000});await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>window.__game.ships.length),2);await page.keyboard.up('c');await page.waitForFunction(()=>document.getElementById('fleet').textContent==='02');assert.equal(await page.locator('.plate:not(.player):not(.enemy) .bar').count(),1);pass('holding C replicates once and shows companion health bar');
 await page.keyboard.down('c');await page.waitForFunction(()=>window.__game.ships.length===3,{},{timeout:15000});await page.keyboard.up('c');pass('second C hold creates third probe');
 const id=await page.evaluate(()=>window.__game.leader.id);await page.keyboard.press('Tab');assert.notEqual(await page.evaluate(()=>window.__game.leader.id),id);pass('Tab switches actively controlled probe');
 await page.evaluate(()=>{window.moves=[];document.addEventListener('mousemove',e=>window.moves.push({x:e.clientX,y:e.clientY,dx:e.movementX,dy:e.movementY,yaw:window.__game.yaw,paused:window.__game.paused,lock:document.pointerLockElement?.id}));});const yaw=await page.evaluate(()=>window.__game.yaw);await page.mouse.move(760,440);await page.mouse.move(890,470,{steps:5});assert.equal(await page.evaluate(yaw=>window.moves.some(m=>Math.abs(m.yaw-yaw)>.001),yaw),true);pass('mouse movement turns probe heading');
 await page.keyboard.press('1');await page.keyboard.press('2');await page.waitForFunction(()=>window.__game.shots.missile>=1&&window.__game.shots.rail>=1);pass('number keys fire missile and railgun');
 await page.keyboard.press('f');assert.equal(await page.evaluate(()=>window.__game.warp),true);await page.keyboard.press('f');assert.equal(await page.evaluate(()=>window.__game.warp),false);pass('F toggles warp mode');
 const dest=await page.evaluate(()=>window.__game.targetPlanet);await page.keyboard.press('n');assert.notEqual(await page.evaluate(()=>window.__game.targetPlanet),dest);await page.keyboard.press('g');assert.equal(await page.evaluate(()=>window.__game.autopilot),true);await page.keyboard.down('a');await page.waitForFunction(()=>!window.__game.autopilot);await page.keyboard.up('a');pass('N selects destination; G navigates; movement cancels navigation');
 await page.evaluate(()=>{const g=window.__game;g.enemies=[];g.ships.forEach(s=>s.hp=100);g.yaw=0;g.pitch=0;g.leader.pos=[0,0,0];g.leader.vel=[0,0,0];g.enemies.push({id:10001,pos:[0,0,-230],hp:100,dir:[0,0,1],fire:100,name:'Test Sentinel'});g.cooldowns.rail=0;});await page.waitForFunction(()=>document.getElementById('reticle').classList.contains('locked'));await page.keyboard.press('2');await page.waitForFunction(()=>window.__game.enemies.length===0||window.__game.enemies[0].hp<100);pass('aim reticle locks sentinel; railgun damages it in rendered scene');
 await page.evaluate(()=>{const g=window.__game;g.enemies=[];g.yaw=0;g.pitch=0;g.leader.pos=[0,0,0];g.leader.vel=[0,0,0];g.ships=[g.leader];g.enemies.push({id:10002,pos:[20,0,-300],hp:100,dir:[0,0,1],fire:100,name:'Test Sentinel'});g.cooldowns.missile=0;});await page.keyboard.press('1');await page.waitForFunction(()=>window.__game.enemies[0]?.hp<100,{},{timeout:15000});pass('homing missile reaches and damages sentinel with rendered effects');
 await page.evaluate(()=>{const g=window.__game;g.enemies=[];for(let i=g.ships.length;i<50;i++)g.replicate();});await page.waitForFunction(()=>document.getElementById('fleet').textContent==='50');assert.equal(await page.evaluate(()=>window.__game.ships.length),50);const formationTime=await page.evaluate(()=>window.__game.time);await page.waitForFunction(t=>window.__game.time>t+2.2,formationTime);assert.ok(await page.locator('.plate:not(.player):not(.enemy)').evaluateAll(es=>es.filter(e=>e.style.display!=='none').length)>40);await page.screenshot({path:'/tmp/replicant-fleet.png'});pass('50-ship fleet renders with companion nameplates and health bars');
 await page.evaluate(()=>{const g=window.__game;g.damage(g.leader,100,'ally');});await page.waitForFunction(()=>window.__game.ships.length===49);assert.equal(await page.locator('#gameover').isVisible(),false);pass('destroyed active probe transfers control to a live companion');
 await page.evaluate(()=>{const g=window.__game;for(const s of g.ships)g.damage(s,100,'ally');});await page.waitForFunction(()=>window.__game.over);assert.equal(await page.locator('#gameover').isVisible(),true);await page.locator('#restart').click();await page.waitForFunction(()=>window.__game.ships.length===1&&!window.__game.over);assert.equal(await page.locator('#pause').isVisible(),true);pass('fleet destruction shows game over and restart resets game');
 await page.setViewportSize({width:1920,height:1080});await page.waitForFunction(()=>window.__render.camera.aspect===1920/1080);assert.equal(await page.evaluate(()=>window.__render.camera.aspect),1920/1080);assert.equal(await page.locator('#resume').isVisible(),true);pass('desktop viewport resizing preserves camera and controls');
 assert.deepEqual(errors,[]);pass('no JavaScript, asset loading, or shader compilation errors');console.log(`\n${passed} browser checks passed.`,capture);
 }catch(e){console.error('Browser errors:',errors);throw e;}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
