let playwright;try{playwright=require('playwright');}catch{playwright=require((process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES||'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules')+'/playwright');}const {chromium}=playwright;
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert/strict');const root=path.resolve(__dirname,'../dist');const types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.jpg':'image/jpeg'};const server=http.createServer((req,res)=>{const file=path.join(root,req.url==='/'?'index.html':req.url.split('?')[0]);fs.readFile(file,(err,data)=>{res.writeHead(err?404:200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(err?'missing':data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||(fs.existsSync('/tmp/replicant-chromium/chromium')?'/tmp/replicant-chromium/chromium':chromium.executablePath()),headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2});const page=await context.newPage(),cdp=await context.newCDPSession(page),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text());});let passed=0;const pass=s=>{passed++;console.log('PASS',s);};const points=new Map();const dispatch=async(type,id,x,y)=>{const ended=points.get(id);if(type==='touchEnd'||type==='touchCancel')points.delete(id);else points.set(id,{x,y,id,radiusX:5,radiusY:5,force:1});const eventPoints=type==='touchEnd'?(points.size&&ended?[ended]:[]):type==='touchCancel'?[]:[...points.values()];await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:eventPoints});};const center=async(sel)=>{const r=await page.locator(sel).boundingBox();return{x:r.x+r.width/2,y:r.y+r.height/2};};const hold=async(sel,id)=>{const p=await center(sel);await dispatch('touchStart',id,p.x,p.y);return p;};const release=async(id)=>dispatch('touchEnd',id);try{
 await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>!document.getElementById('start').disabled);assert.equal(await page.locator('#mode-touch').getAttribute('aria-pressed'),'true');assert.equal(await page.evaluate(()=>window.__touch.enabled),true);pass('touch devices automatically select mobile mode');await page.locator('#name').fill('Chris Mobile');await page.locator('#start').tap();await page.waitForFunction(()=>window.__game?.paused);assert.equal(await page.locator('#touch-guide').isVisible(),true);assert.equal(await page.locator('.controls').isVisible(),false);await page.locator('#resume').tap();await page.waitForFunction(()=>!window.__game.paused);assert.equal(await page.evaluate(()=>document.pointerLockElement),null);pass('mobile start shows touch guide and resumes without mouse capture');await page.waitForFunction(()=>window.__render.renderer.info.render.calls>0);await page.screenshot({path:'/tmp/replicant-mobile-portrait.png'});
 assert.equal(await page.locator('#touch-controls').isVisible(),true);for(const sel of ['#move-stick','#look-stick','.touch-actions','.touch-tools']){const r=await page.locator(sel).boundingBox();assert.ok(r.x>=0&&r.y>=0&&r.x+r.width<=390.5&&r.y+r.height<=844.5,sel);}const actionBox=await page.locator('.touch-actions').boundingBox(),moveBox=await page.locator('#move-stick').boundingBox();assert.ok(moveBox.x+moveBox.width<actionBox.x);pass('portrait controls are on screen with separate thumb regions');
 await page.evaluate(()=>{window.pe=[];for(const event of ['pointerdown','pointerup','pointercancel','lostpointercapture'])document.addEventListener(event,e=>window.pe.push({event,id:e.pointerId,target:e.target.id}),true);});const move=await center('#move-stick'),aim=await center('#look-stick');const before=await page.evaluate(()=>({pos:[...window.__game.leader.pos],yaw:window.__game.yaw}));await dispatch('touchStart',1,move.x,move.y);await dispatch('touchMove',1,move.x+20,move.y-30);await dispatch('touchStart',2,aim.x,aim.y);await dispatch('touchMove',2,aim.x+25,aim.y-10);await page.waitForFunction(b=>window.__game.leader.pos[2]<b.pos[2]-10&&window.__game.yaw>b.yaw+.1,before);assert.ok(await page.evaluate(()=>window.__touch.axes.moveX>0&&window.__touch.axes.moveY<0&&window.__touch.axes.lookX>0));pass('two simultaneous real touches move and aim independently');await release(2);await page.waitForFunction(()=>window.__touch.axes.lookX===0);assert.equal(await page.evaluate(()=>window.__touch.axes.lookX),0);assert.ok(await page.evaluate(()=>window.__touch.axes.moveY<0));await release(1);await page.waitForFunction(()=>window.__touch.axes.moveY===0);assert.equal(await page.evaluate(()=>window.__touch.axes.moveY),0);pass('releasing one stick leaves the other active and release resets axes');
 const shots=await page.evaluate(()=>({...window.__game.shots}));await page.locator('[data-fire=missile]').tap();await page.locator('[data-fire=rail]').tap();await page.waitForFunction(s=>window.__game.shots.missile>s.missile&&window.__game.shots.rail>s.rail,shots);pass('touch weapon taps fire immediately');
 const y=await page.evaluate(()=>window.__game.leader.pos[1]);await hold('[data-held=up]',3);await page.waitForFunction(y=>window.__game.leader.pos[1]>y+15,y);await release(3);const y2=await page.evaluate(()=>window.__game.leader.pos[1]);await hold('[data-held=down]',3);await page.waitForFunction(y=>window.__game.leader.pos[1]<y-10,y2);await release(3);pass('Rise and Descend buttons move vertically');
 await hold('[data-held=c]',3);await page.waitForFunction(()=>window.__game.ships.length===2,{},{timeout:15000});await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>window.__game.ships.length),2);await release(3);await hold('[data-held=c]',3);await page.waitForFunction(()=>window.__game.ships.length===3,{},{timeout:15000});await release(3);pass('hold Clone creates one ship per hold and supports quick re-holding');
 const leader=await page.evaluate(()=>window.__game.leader.id);await page.locator('[data-touch-action=switch]').tap();assert.notEqual(await page.evaluate(()=>window.__game.leader.id),leader);pass('Switch button changes piloted probe');
 await page.locator('#touch-warp').tap();assert.equal(await page.evaluate(()=>window.__game.warp),true);await page.locator('#touch-warp').tap();assert.equal(await page.evaluate(()=>window.__game.warp),false);const target=await page.evaluate(()=>window.__game.targetPlanet);await page.locator('[data-touch-action=next]').tap();assert.notEqual(await page.evaluate(()=>window.__game.targetPlanet),target);await page.locator('#touch-nav').tap();assert.equal(await page.evaluate(()=>window.__game.autopilot),true);await hold('#move-stick',1);await dispatch('touchMove',1,move.x,move.y-30);await page.waitForFunction(()=>!window.__game.autopilot);await release(1);pass('mobile warp, destination selection, navigation and manual cancellation work');
 await hold('[data-held=boost]',3);const start=await page.evaluate(()=>window.__game.time);await hold('#move-stick',1);await dispatch('touchMove',1,move.x,move.y-38);await page.waitForFunction(t=>window.__game.time>t+.8,start);assert.ok(await page.evaluate(()=>Math.hypot(...window.__game.leader.vel)>150));await release(1);await release(3);await hold('[data-held=brake]',3);await page.waitForFunction(()=>Math.hypot(...window.__game.leader.vel)<2);await release(3);pass('boost works simultaneously with joystick; brake stops ship');
 const swipeBefore=await page.evaluate(()=>window.__game.yaw);await dispatch('touchStart',4,195,365);await dispatch('touchMove',4,245,330);await release(4);assert.ok(await page.evaluate(b=>window.__game.yaw>b+.2,swipeBefore));pass('swiping free space provides direct aiming');
 await hold('[data-held=c]',3);await dispatch('touchCancel',3);assert.equal(await page.evaluate(()=>window.__touch.held.size),0);assert.equal(await page.evaluate(()=>window.__game.cloneLatch),false);pass('interrupted touches release held buttons safely');
 await page.locator('#pause-button').tap();await page.waitForFunction(()=>window.__game.paused);const t=await page.evaluate(()=>window.__game.time);await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>window.__game.time),t);assert.equal(await page.locator('#touch-guide').isVisible(),true);assert.equal(await page.evaluate(()=>window.__touch.held.size),0);pass('touch Pause freezes simulation, clears inputs and shows guide');
 await page.locator('#input-mode-pause').tap();assert.equal(await page.evaluate(()=>window.__touch.enabled),false);assert.equal(await page.locator('.controls').isVisible(),true);await page.locator('#input-mode-pause').tap();assert.equal(await page.evaluate(()=>window.__touch.enabled),true);pass('control modes can be changed from pause without resetting game');
 await page.setViewportSize({width:844,height:390});await page.waitForFunction(()=>window.__render.camera.aspect===844/390);await page.locator('#resume').tap();await page.waitForFunction(()=>!window.__game.paused);for(const sel of ['#move-stick','#look-stick','.touch-actions','.touch-tools']){const r=await page.locator(sel).boundingBox();assert.ok(r.x>=0&&r.y>=0&&r.x+r.width<=844.5&&r.y+r.height<=390.5,sel);}await page.screenshot({path:'/tmp/replicant-mobile-landscape.png'});pass('landscape rotation adapts camera and keeps all touch controls reachable');
 await page.setViewportSize({width:320,height:568});await page.waitForFunction(()=>window.__render.camera.aspect===innerWidth/innerHeight);console.log('SMALL VIEW',await page.evaluate(()=>({width:innerWidth,height:innerHeight,scroll:document.documentElement.scrollWidth,aspect:window.__render.camera.aspect})));assert.equal(await page.evaluate(()=>innerWidth),320);const left=await page.locator('#move-stick').boundingBox(),right=await page.locator('#look-stick').boundingBox(),middle=await page.locator('.touch-actions').boundingBox();assert.ok(left.x+left.width<middle.x&&middle.x+middle.width<right.x);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/replicant-mobile-small.png'});pass('small 320px phone has no overlapping controls or horizontal overflow');
 assert.deepEqual(errors,[]);pass('mobile session reports no JavaScript or shader errors');console.log(`\n${passed} mobile browser checks passed.`);
 }catch(e){console.error('Browser errors:',errors);throw e;}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
